version: '2'
services:
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
  location:
    image: egovio/location:latest
    ports:
      - "8080:8080"
      - "9990:9990"
    links:
      - postgres:pghost
    environment:
      - DB_HOST=pghost
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypass
      - REDIS_HOST=redis
      - CORS_ENABLED=true
      - MASTER_SERVER=false
