version: '2'
services:
  postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/pg/data/
    ports:
      - "5432:5432"
    volumes:
      - ./pg-container-data:/var/lib/pg/data